apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: nfs.example.com
    path: /var/export/data/wp
